export const projects = [
  {
    title: '11 Years',
    description: "'11 Years' is a 3-D marine survival game where you play as a Clownfish trying to survive from the direct and indirect human influences on the coral reef ecosystem.",
    image: '/images/1.png',
    tags: ['C#', 'Unity', 'Game Designer', 'Level Designer'],
    visit: 'https://gameheads.itch.io/11-years',
    id: 0,
    duties: "As part of my role in developing a 3D marine world game, I was responsible for implementing design specifications and technical limitations. In addition, I established various metrics such as movement speed, object animation speed, object spawn rate, and metric properties of player and enemy objects to ensure a balanced gameplay experience.",
    accomplishments: "I accomplished a variety of tasks while developing 11 Years, a 3D marine survival game where players assume the role of a Clownfish and try to survive in a coral reef ecosystem affected by direct and indirect human influences. One of my main responsibilities was implementing design specifications and technical limitations to help establish the game's overall design and feel. Another significant accomplishment was implementing the Clownfish's ability to eat and complete objectives. Through these efforts, our team aims to educate players about the dire situation in our marine ecosystems and contribute to the climate change dialogue while conveying the experiences that wildlife animals have to endure because of human impact.",
  },
  {
    title: 'Confined Indorms',
    description:"An isometric, interactive, non-linear management game where you choose your own tasks to complete in the dorm stuck in quarantine.",
    image: '/images/2.png',
    tags: ['C#', 'Unity'],
    visit: 'https://gameheads.itch.io/confined-indorms',
    id: 1,
    duties: "During my work on a game development project, I played a crucial role in managing a cross-functional team of seven members by enforcing Scrum and other industry project management frameworks. I oversaw the completion of over 120 deliverables, issues, and feedback to ensure the project stayed on track and met its deadlines. Additionally, I implemented C# scripts for various aspects of the game, such as UI elements, animations, dialogue, music, visual add-ons, and event systems, which contributed significantly to the game's overall functionality and aesthetic. Finally, I corresponded with 11 stakeholders and 9 experts to conduct A/B testing for the minimum viable prototype stages in development, ensuring that the game was refined and met the needs and preferences of its intended audience.",
  },
  {
    title: 'SpectrCare',
    description:"MySpectorHome, an iOS proof-of-concept app, is where residents can support to the underserved community, and pinpoint street encampments that need extra assistance.",
    image: '/images/4.webp',
    tags: ['Winner', 'Swift', 'iOS', 'Figma', 'UX/UI', 'Rest API'],
    source: 'https://github.com/HarryZ10/mySpectr',
    visit: 'https://www.youtube.com/watch?v=-Q0xte4u9N0',
    id: 2,
    summary: 'Summary',
    accomplishments: "SpectrCare is an iOS application developed under the College Track Swift App Development class from February to June of 2021. This app was awarded Best User Interface in the College Track NorCal Showcase of 2021. The showcase included 73 participants and 7 design awards. This project was the only app that had a functional application and tangible user interactivity.",
  },
  {
    title: 'Pickabox',
    description: "Pickabox is a user-friendly web application where everyday Wikipedia users dive deep and learn from API-generated informational articles.",
    image: '/images/3.png',
    tags: ['Winner', 'React', 'Node', 'Python', 'Google Cloud Backend'],
    source: 'https://github.com/HarryZ10/pickabox.space',
    visit: 'https://pickaboxdemo.netlify.app/',
    id: 3,
    summary: 'Pickabox (revised 2023) is a user-friendly web application where everyday Wikipedia users dive deep and learn from API-generated informational articles',
    accomplishments: "Pickabox, an automatic organizer and random generator of wikis upon wikis, is a user-friendly web application where everyday Wikipedia users generate random Wikipedia pages on our platform. It is truly the organizational tool to help you keep track of what you’re reading and learning.",
  },
  {
    title: 'Custom Event Portal',
    description: "A hackathon dashboard for ACM @ GFU, where students will work collaboratively on a team to build a technical project in 30 hours.",
    image: '/images/6.png',
    tags: ['React', 'Node', 'Gitlab API', 'Python', 'Rest API'],
    visit: 'https://live-foxacmw-com.vercel.app/',
    id: 4,
    summary: 'A weekend-long hackathon, hosted by ACM @ GFU, where students will work collaboratively on a team to build a technical project in 30 hours.',
    duties: "In my role as Head of Marketing from 2021-22, I was responsible for delivering weekly test and release of over 5 production builds for ACM-associated websites, utilizing the primary technology stack which included React, Node, and Express. My efforts in this area ensured that ACM was being advertised effectively to its target audience. Additionally, I created and maintained over 3 brand posts per week to promote and market club events to more than 2000 George Fox UG students on social media platforms, such as Instagram and LinkedIn. By doing so, I was able to generate a significant level of engagement and interest in the club's activities among the university's student body. Through my work, I was able to increase ACM's visibility and promote its events to a wider audience, thereby contributing to its overall success.",
  },
];
